# Generated by Django 5.0.4 on 2024-08-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_item_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="")),
            ],
        ),
    ]
