# Generated by Django 5.0.4 on 2024-08-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.TextField(default=""),
        ),
    ]
